**Data Structures**

**1. Tuple**

In standard Python the main data structures used to represent vectors are: tuples and lists. 
What a tuple is? A tuple may be defined by enumerating it's elements between two parentheses, separating them with commas. A single tuple can hold elements of various types.

In [1]:
vec_tuple = (-1, 8,9,12.2,41, "something here", 100)
print(vec_tuple)

(-1, 8, 9, 12.2, 41, 'something here', 100)


We can access the elements of a tuple by indexing, using square brakets. [ ].

**Attention**: in Python indexing starts from 0 so, our element at position 2 will be the 3rd element. 

But what if we want to access more than only one element? We way use the sequence function : 
 


In [9]:
print(vec_tuple[2])
print(vec_tuple[1:3])
print(vec_tuple[1:4:1])# it has the logic   start:to:step  pay attention that slice indices must be integers

9
(8, 9)
(8, 9, 12.2)


The number of elements in a tuple can be accessed by calling the built-in *len( )* function.



In [10]:
len(vec_tuple)

7

**2. Lists**

Lists are extremely flexible and easy to use. We creat e alist in python using the syntax *name_list=[ ]*

In [14]:
mylist_list=[2,3,4,3,2,12,3,"city"]
print(mylist_list)# thsi will print our list
type(mylist_list) # this will return teh type of our object


[2, 3, 4, 3, 2, 12, 3, 'city']


list

What if we want to access elements on our list. Same as in tuple we use [ ]. We may add, remove elements from our list by using functions such as: append ,pop 

In [23]:
print(mylist_list[3])# print the 4th element in my list
print(mylist_list[3]=="Alda")# check the value of the 4th element if it is "Alda". True or False will be returned
mylist_list[3]=1000 # change the value of the 4th element to a value of 1000. 
print(mylist_list)

1000
False
[2, 3, 4, 1000, 2, 12, 3, 'city', ['country']]


What if I want to add a new list to my existing list? Or to remove an element?

In [24]:
mylist_list.append(["country"]) # adding the list [country] to the end of our list
print(mylist_list)

mylist_list.pop(1) # removing the element at the index "1"
print(mylist_list)



[2, 3, 4, 1000, 2, 12, 3, 'city', ['country'], ['country']]
[2, 4, 1000, 2, 12, 3, 'city', ['country'], ['country']]


**3. Arrays and NumPy **

First, we import the *numpy* library. (To save on the characters, it is customary to import it as np.)


In [25]:
import numpy as np
X_array = np.array([23.7, 114.5, -24.7, 52.1423, -13.64, 8.0001]) # creating a NumPy array from a Python list
print(X_array)


[ 23.7    114.5    -24.7     52.1423 -13.64     8.0001]


If we want to initialize an array in python from 0 or 1 we use the following functions respectively:

In [31]:
np.ones(shape=10) # initializing a NumPy array from scratch using ones with length 10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.zeros(shape=10)# initializing a NumPy array from scratch using zeros with length 10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

We can even initialize NumPy arrays using random numbers. Since they are random we will have different results every time we run the code unless we save the result as an object.

In [41]:
print(np.random.rand(20))
my_array=np.random.rand(20)# create an array and save it as my_array
print(my_array)# print the result
type(my_array)

[0.15921256 0.11933821 0.45101546 0.67906976 0.23490699 0.5519705
 0.86650291 0.49286486 0.37460128 0.60154512 0.89233479 0.68173552
 0.61228763 0.09716854 0.16087454 0.71346262 0.10405685 0.62797829
 0.95065    0.02204558]
[0.99067405 0.05865646 0.48878197 0.59815275 0.70084361 0.19151317
 0.94468597 0.87900856 0.94559402 0.51015539 0.06789301 0.1106832
 0.84699156 0.01425649 0.73826039 0.00993075 0.72839227 0.07304864
 0.8218333  0.31740198]


numpy.ndarray

What if we want to initialize an array with same dimensions as an existing one? There are three main options using: *np.zeros_like, np.ones_like, and np.empty_like* functions. 

In [36]:
print(np.zeros_like(my_array))
print(np.ones_like(my_array))
print(np.empty_like(my_array))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [44]:
print(my_array[3])# print the 4th element 
print(my_array[1:5])# print elements from 2nd to 6th

0.5981527506130188
[0.05865646 0.48878197 0.59815275 0.70084361]


In [47]:
my_array[1]=10000 # substitute a value with a new one
print(my_array)

[9.90674046e-01 1.00000000e+04 4.88781970e-01 1.00000000e+04
 7.00843613e-01 1.91513169e-01 9.44685969e-01 8.79008565e-01
 9.45594018e-01 5.10155386e-01 6.78930117e-02 1.10683196e-01
 8.46991562e-01 1.42564880e-02 7.38260389e-01 9.93075343e-03
 7.28392271e-01 7.30486387e-02 8.21833298e-01 3.17401977e-01]


**4. Vectors and NumPy**

Now let's focus on how we create vectors in python using the function *np.array()*.

In [57]:
vec_1 = np.array([-12.0, 16.9, 21.37, 40,23,100.02])
print(vec_1)
vec_2 = np.array([-18.33, -39.64, -47.77,45, 76,98])
print(vec_2)
len(vec_1)==len(vec_2) # do the vectors have the same dimenssion


[-12.    16.9   21.37  40.    23.   100.02]
[-18.33 -39.64 -47.77  45.    76.    98.  ]


True

Can we do basic mathematical operations with vectors? Of course, just pay attention they are done at this step element per element.

In [56]:
print(vec_1 + vec_2) 
print(3*vec_2)
print(vec_1*3+vec_2/5)


[-30.33 -22.74 -26.4   85.    99.   198.02]
[ -54.99 -118.92 -143.31  135.    228.    294.  ]
[-39.666  42.772  54.556 129.     84.2   319.66 ]


Now you know how to create and manipulate with tuples, list, arrays and vectors in Python!